###查询所有商品

Get Http://localhost:8080/items HTTP/1.1

###查询一个商品
Get Http://localhost:8080/items/57 HTTP/1.1

###添加一个商品
POST Http://localhost:8080/items/ HTTP/1.1
Content-Type: application/json

{
  "name": "红米k40 pro",
  "type": "骁龙888",
  "brand": "红米",
  "count": 500,
  "price": 3300.0,
  "sort": "平板电脑",
  "picture": ""
}

###更新一个商品
PUT Http://localhost:8080/items/62 HTTP/1.1
Content-Type: application/json

{
  "id":"62",
  "name": "红米k40 pro+",
  "type": "骁龙888",
  "brand": "红米",
  "count": 500,
  "price": 3300.0,
  "sort": "平板电脑",
  "picture": "64.png"
}

###删除一个商品
DELETE Http://localhost:8080/items/62 HTTP/1.1